"""initial_schema

Revision ID: baeffd94ede2
Revises: 
Create Date: 2026-09-27 01:32:51.718919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baeffd94ede2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breakers_source_name'), 'circuit_breakers', ['source_name'], unique=True)
    op.create_table('discard_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discard_created', 'discard_ledger', ['created_at'], unique=False)
    op.create_index('ix_discard_external', 'discard_ledger', ['external_id'], unique=False)
    op.create_index(op.f('ix_discard_ledger_run_id'), 'discard_ledger', ['run_id'], unique=False)
    op.create_index('ix_discard_run', 'discard_ledger', ['run_id'], unique=False)
    op.create_index('ix_discard_source_stage', 'discard_ledger', ['source', 'stage'], unique=False)
    op.create_index('ix_discard_url', 'discard_ledger', ['url'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('normalized_company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('work_mode', sa.String(length=32), nullable=False),
    sa.Column('seniority', sa.String(length=32), nullable=False),
    sa.Column('employment_type', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nice_to_have', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_status', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('alternative_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('content_hash', name='uq_jobs_content_hash'),
    sa.UniqueConstraint('uuid', name='uq_jobs_uuid')
    )
    op.create_index('ix_jobs_company', 'jobs', ['company'], unique=False)
    op.create_index('ix_jobs_discovered', 'jobs', ['discovered_at'], unique=False)
    op.create_index('ix_jobs_published', 'jobs', ['published_at'], unique=False)
    op.create_index('ix_jobs_source', 'jobs', ['source'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_uuid', 'jobs', ['uuid'], unique=False)
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('duplicates_count', sa.Integer(), nullable=False),
    sa.Column('discarded_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('notified_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('discard_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_started', 'search_runs', ['started_at'], unique=False)
    op.create_index('ix_run_status', 'search_runs', ['status'], unique=False)
    op.create_index(op.f('ix_search_runs_run_id'), 'search_runs', ['run_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('seniority', sa.String(length=32), nullable=False),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resume_file_path', sa.String(length=512), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('job_changelogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_changelog_created', 'job_changelogs', ['created_at'], unique=False)
    op.create_index('ix_changelog_job', 'job_changelogs', ['job_id'], unique=False)
    op.create_index('ix_changelog_job_field', 'job_changelogs', ['job_id', 'field_name'], unique=False)
    op.create_table('job_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_feedback')
    )
    op.create_index('ix_feedback_job', 'job_feedbacks', ['job_id'], unique=False)
    op.create_index('ix_feedback_user', 'job_feedbacks', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', 'channel', 'event_type', name='uq_notifications_logical'),
    sa.UniqueConstraint('user_id', 'job_id', 'channel', name='uq_notifications_user_job_channel')
    )
    op.create_index('ix_notif_channel', 'notifications', ['channel'], unique=False)
    op.create_index('ix_notif_job', 'notifications', ['job_id'], unique=False)
    op.create_index('ix_notif_outbox', 'notifications', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_notif_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('search_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desired_roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mandatory_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excluded_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seniority_levels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('regions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('areas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('work_modes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('minimum_salary', sa.Float(), nullable=True),
    sa.Column('maximum_salary', sa.Float(), nullable=True),
    sa.Column('employment_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_companies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excluded_companies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excluded_jobs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('max_job_age_days', sa.Integer(), nullable=False),
    sa.Column('minimum_match_score', sa.Integer(), nullable=False),
    sa.Column('search_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=128), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('discord_webhook_url', sa.String(length=512), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_digest_mode', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_preferences_user_id'), 'search_preferences', ['user_id'], unique=True)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_favorite')
    )
    op.create_index('ix_fav_job', 'user_favorites', ['job_id'], unique=False)
    op.create_index('ix_fav_user', 'user_favorites', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_jobs_analyzed', sa.Integer(), nullable=False),
    sa.Column('total_compatible', sa.Integer(), nullable=False),
    sa.Column('total_new', sa.Integer(), nullable=False),
    sa.Column('total_remote', sa.Integer(), nullable=False),
    sa.Column('total_hybrid', sa.Integer(), nullable=False),
    sa.Column('total_onsite', sa.Integer(), nullable=False),
    sa.Column('total_internships', sa.Integer(), nullable=False),
    sa.Column('top_jobs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('presented_job_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_created', 'weekly_reports', ['created_at'], unique=False)
    op.create_index('ix_weekly_user', 'weekly_reports', ['user_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('skills_score', sa.Integer(), nullable=False),
    sa.Column('seniority_score', sa.Integer(), nullable=False),
    sa.Column('location_score', sa.Integer(), nullable=False),
    sa.Column('role_score', sa.Integer(), nullable=False),
    sa.Column('salary_score', sa.Integer(), nullable=False),
    sa.Column('recency_score', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_job_match_profile')
    )
    op.create_index('ix_match_job', 'job_matches', ['job_id'], unique=False)
    op.create_index('ix_match_profile', 'job_matches', ['profile_id'], unique=False)
    op.create_index('ix_match_score', 'job_matches', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_score', table_name='job_matches')
    op.drop_index('ix_match_profile', table_name='job_matches')
    op.drop_index('ix_match_job', table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index('ix_weekly_user', table_name='weekly_reports')
    op.drop_index('ix_weekly_created', table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index('ix_fav_user', table_name='user_favorites')
    op.drop_index('ix_fav_job', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_search_preferences_user_id'), table_name='search_preferences')
    op.drop_table('search_preferences')
    op.drop_index('ix_notif_user_status', table_name='notifications')
    op.drop_index('ix_notif_outbox', table_name='notifications')
    op.drop_index('ix_notif_job', table_name='notifications')
    op.drop_index('ix_notif_channel', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_feedback_user', table_name='job_feedbacks')
    op.drop_index('ix_feedback_job', table_name='job_feedbacks')
    op.drop_table('job_feedbacks')
    op.drop_index('ix_changelog_job_field', table_name='job_changelogs')
    op.drop_index('ix_changelog_job', table_name='job_changelogs')
    op.drop_index('ix_changelog_created', table_name='job_changelogs')
    op.drop_table('job_changelogs')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_runs_run_id'), table_name='search_runs')
    op.drop_index('ix_run_status', table_name='search_runs')
    op.drop_index('ix_run_started', table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index('ix_jobs_uuid', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_source', table_name='jobs')
    op.drop_index('ix_jobs_published', table_name='jobs')
    op.drop_index('ix_jobs_discovered', table_name='jobs')
    op.drop_index('ix_jobs_company', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_discard_url', table_name='discard_ledger')
    op.drop_index('ix_discard_source_stage', table_name='discard_ledger')
    op.drop_index('ix_discard_run', table_name='discard_ledger')
    op.drop_index(op.f('ix_discard_ledger_run_id'), table_name='discard_ledger')
    op.drop_index('ix_discard_external', table_name='discard_ledger')
    op.drop_index('ix_discard_created', table_name='discard_ledger')
    op.drop_table('discard_ledger')
    op.drop_index(op.f('ix_circuit_breakers_source_name'), table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    # ### end Alembic commands ###
